Add necessary check after documentation build (#491)
* Add documentation generation checks

* Test the check by not generating the doc

* Fix doc check

* Add back doc generation

* Improve check failure message.

* Add a size check.

* Revert "Add a size check."

This reverts commit 52e202a7efdba05f17389cce9556326ae53c8a56.

* Revert "Improve check failure message."

This reverts commit 2d7c0c5c34528d0967a02cab76322b5bbee443eb.

* Revert "Revert "Improve check failure message.""

This reverts commit ed700c477cf4d01dc8de78f01b77fc69e5b59918.

* Revert "Revert "Add a size check.""

This reverts commit 332d950df12d402f5f339b57bf5ef6b800c8db73.

* Parse the log to check for success

* Parse the log to check for success

* Parse the log to check for success

* Parse the log to check for success

* Parse the log to check for success

* Fix sphinx errors and warnings

* try a time-out of 40 min

* force sphinx to 0.5.1

* force sphinx to 5.1.0

* force sphinx to 5.1.1

* Set time-out back to 20mn

* Improve success test

* Improve success test

* Improve success test

* Improve message and remove commented tests.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -257,6 +257,22 @@ jobs:
           build_doc.bat > ..\docs\log.txt && type ..\docs\log.txt 2>&1
         timeout-minutes: 20
 
+      - name: "Check for success"
+        shell: bash
+        working-directory: docs
+        run: |
+          case `tail -n 5 log.txt | grep -F "build succeeded" >/dev/null; echo $?` in
+          0)
+            echo "Build succeeded!"
+            exit 0;;
+          1)
+            echo "Documentation generation failed, please check previous step!"
+            exit 1;;
+          *)
+            echo "An error occurred while checking success of the previous step!"
+            exit 1;;
+          esac
+
       - name: "Kill all servers"
         uses: pyansys/pydpf-actions/kill-dpf-servers@v2.2.dev1
         if: always()
