Improve success test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -261,15 +261,15 @@ jobs:
         working-directory: docs
         run: |
           case `tail -n 5 log.txt | grep -F "build succeeded" >/dev/null; echo $?` in
-            0)
-              echo "Build succeeded!"
-              exit 0
-            1)
-              echo "Build failed!"
-              exit 1
-            *)
-              echo "An error occurred!"
-              exit 1
+          0)
+            echo "Build succeeded!"
+            exit 0;;
+          1)
+            echo "Build failed!"
+            exit 1;;
+          *)
+            echo "An error occurred!"
+            exit 1;;
           esac
 
 #      - name: "Check for successful generation"
